export const GSF_HEADERS = [
  'year',
  'cloud-provider',
  'cloud-region',
  'cfe-region',
  'em-zone-id',
  'wt-region-id',
  'location',
  'geolocation',
  'cfe-hourly',
  'cfe-annual',
  'power-usage-efficiency',
  'net-carbon',
  'grid-carbon-intensity-24x7',
  'grid-carbon-intensity-consumption',
  'grid-carbon-intensity-marginal',
  'grid-carbon-intensity-production',
  'grid-carbon-intensity',
];

export const AZURE_HEADERS = [
  'cpu-cores-available',
  'cpu-cores-utilized',
  'cpu-manufacturer',
  'cpu-model-name',
  'cpu-tdp',
  'gpu-count',
  'gpu-model-name',
  'gpu-tdp',
  'instance-class',
  'memory-available',
];

export const AWS_HEADERS = [
  'cpu-cores-available',
  'cpu-cores-utilized',
  'cpu-manufacturer',
  'cpu-model-name',
  'cpu-tdp',
  'gpu-count',
  'gpu-model-name',
  'Hardware Information on AWS Documentation & Comments',
  'instance-class',
  'instance-storage',
  'memory-available',
  'platform-memory',
  'release-date',
  'storage-drives',
];
